name: CI

on:
  workflow_dispatch:
  push:
    branches: ["main", "fix-workflow","unittest"]
  pull_request:
    branches: ["main"]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello-world"

  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: "3.11"
        - run: pip install poetry
        - run: poetry install --no-interaction --no-ansi
        - run: poetry run pytest

  build-docker:
    runs-on: ubuntu-latest
    #needs: test

    steps:
      - uses: actions/checkout@v4
      - run: docker build -t tp-fastapi-ci:ci .
